services:
  web:
    image: prrolls-web
    dns:
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - VIRTUAL_HOST=${APP_HOST},www.${APP_HOST}
      - LETSENCRYPT_HOST=${APP_HOST},www.${APP_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - rails_tmp:/rails/tmp
      - rails_log:/rails/log
    depends_on:
      - postgresql
    networks:
      - app_network

  postgresql:
    image: postgres:16.1
    container_name: pr_rolls_postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app_network

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
    restart: always
    networks:
      - app_network

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always
    networks:
      - app_network

networks:
  app_network:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "172.28.0.0/16"
        - subnet: "fd00:dead:beef::/48"

volumes:
  dbdata:
  rails_tmp:
  rails_log:
  certs:
  acme:
  html:
