services:
  web:
    build: .
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - VIRTUAL_HOST=${APP_HOST},www.${APP_HOST}
      - LETSENCRYPT_HOST=${APP_HOST},www.${APP_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    expose:
      - "3000"
    volumes:
      - rails_tmp:/rails/tmp
      - rails_log:/rails/log
      - rails_storage:/rails/storage
    depends_on:
      - postgresql

  postgresql:
    image: postgres:16.1
    container_name: pr_rolls_postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    restart: always

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    restart: always

volumes:
  dbdata:
  rails_tmp:
  rails_log:
  rails_storage:
  certs:
